apps/block_scout_web/lib/block_scout_web/admin_router.ex
defmodule BlockScoutWeb.AdminRouter do
  @moduledoc """
  Router for admin pages.
  """

  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.FetchUserFromSession
  alias BlockScoutWeb.Plug.Admin.{CheckOwnerRegistered, RequireAdminRole}

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :check_configured do
    plug(CheckOwnerRegistered)
  end

  pipeline :ensure_admin do
    plug(FetchUserFromSession)
    plug(RequireAdminRole)
  end

  scope "/setup", BlockScoutWeb.Admin do
    pipe_through([:browser])

    get("/", SetupController, :configure)
    post("/", SetupController, :configure_admin)
  end

  scope "/login", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured])

    get("/", SessionController, :new)
    post("/", SessionController, :create)
  end

  scope "/", BlockScoutWeb.Admin do
    pipe_through([:browser, :check_configured, :ensure_admin])

    get("/", DashboardController, :index)

    scope "/tasks" do
      get("/create_contract_methods", TaskController, :create_contract_methods, as: :create_contract_methods)
    end
  end
end

apps/block_scout_web/lib/block_scout_web/router.ex
defmodule BlockScoutWeb.Router do
  use BlockScoutWeb, :router

  alias BlockScoutWeb.Plug.GraphQL

  forward("/wobserver", Wobserver.Web.Router)
  forward("/admin", BlockScoutWeb.AdminRouter)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(BlockScoutWeb.CSPHeader)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/api/v1", BlockScoutWeb.API.V1, as: :api_v1 do
    pipe_through(:api)

    get("/supply", SupplyController, :supply)

    resources("/decompiled_smart_contract", DecompiledSmartContractController, only: [:create])
    resources("/verified_smart_contracts", VerifiedSmartContractController, only: [:create])
  end

  scope "/api", BlockScoutWeb.API.RPC do
    pipe_through(:api)

    alias BlockScoutWeb.API.RPC

    forward("/", RPCTranslator, %{
      "block" => RPC.BlockController,
      "account" => RPC.AddressController,
      "logs" => RPC.LogsController,
      "token" => RPC.TokenController,
      "stats" => RPC.StatsController,
      "contract" => RPC.ContractController,
      "transaction" => RPC.TransactionController
    })
  end

  # Needs to be 200 to support the schema introspection for graphiql
  @max_complexity 200

  forward("/graphql", Absinthe.Plug,
    schema: BlockScoutWeb.Schema,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  forward("/graphiql", Absinthe.Plug.GraphiQL,
    schema: BlockScoutWeb.Schema,
    interface: :advanced,
    default_query: GraphQL.default_query(),
    socket: BlockScoutWeb.UserSocket,
    analyze_complexity: true,
    max_complexity: @max_complexity
  )

  # Disallows Iframes (write routes)
  scope "/", BlockScoutWeb do
    pipe_through(:browser)
  end

  # Allows Iframes (read-only routes)
  scope "/", BlockScoutWeb do
    pipe_through([:browser, BlockScoutWeb.Plug.AllowIframe])

    resources("/", ChainController, only: [:show], singleton: true, as: :chain)

    resources("/market_history_chart", Chain.MarketHistoryChartController,
      only: [:show],
      singleton: true
    )

    resources "/blocks", BlockController, only: [:index, :show], param: "hash_or_number" do
      resources("/transactions", BlockTransactionController, only: [:index], as: :transaction)
    end

    get("/reorgs", BlockController, :reorg, as: :reorg)

    get("/uncles", BlockController, :uncle, as: :uncle)

    resources("/pending_transactions", PendingTransactionController, only: [:index])

    resources("/recent_transactions", RecentTransactionsController, only: [:index])

    get("/txs", TransactionController, :index)

    resources "/tx", TransactionController, only: [:show] do
      resources(
        "/internal_transactions",
        TransactionInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/raw_trace",
        TransactionRawTraceController,
        only: [:index],
        as: :raw_trace
      )

      resources("/logs", TransactionLogController, only: [:index], as: :log)

      resources("/token_transfers", TransactionTokenTransferController,
        only: [:index],
        as: :token_transfer
      )
    end

    resources("/accounts", AddressController, only: [:index])

    resources "/address", AddressController, only: [:show] do
      resources("/transactions", AddressTransactionController, only: [:index], as: :transaction)

      resources(
        "/internal_transactions",
        AddressInternalTransactionController,
        only: [:index],
        as: :internal_transaction
      )

      resources(
        "/validations",
        AddressValidationController,
        only: [:index],
        as: :validation
      )

      resources(
        "/contracts",
        AddressContractController,
        only: [:index],
        as: :contract
      )

      resources(
        "/decompiled_contracts",
        AddressDecompiledContractController,
        only: [:index],
        as: :decompiled_contract
      )

      resources(
        "/logs",
        AddressLogsController,
        only: [:index],
        as: :logs
      )

      resources(
        "/contract_verifications",
        AddressContractVerificationController,
        only: [:new, :create],
        as: :verify_contract
      )

      resources(
        "/read_contract",
        AddressReadContractController,
        only: [:index, :show],
        as: :read_contract
      )

      resources("/tokens", AddressTokenController, only: [:index], as: :token) do
        resources(
          "/token_transfers",
          AddressTokenTransferController,
          only: [:index],
          as: :transfers
        )
      end

      resources(
        "/token_balances",
        AddressTokenBalanceController,
        only: [:index],
        as: :token_balance
      )

      resources(
        "/coin_balances",
        AddressCoinBalanceController,
        only: [:index],
        as: :coin_balance
      )

      resources(
        "/coin_balances/by_day",
        AddressCoinBalanceByDayController,
        only: [:index],
        as: :coin_balance_by_day
      )
    end

    resources "/tokens", Tokens.TokenController, only: [:show], as: :token do
      resources(
        "/token_transfers",
        Tokens.TransferController,
        only: [:index],
        as: :transfer
      )

      resources(
        "/read_contract",
        Tokens.ReadContractController,
        only: [:index],
        as: :read_contract
      )

      resources(
        "/token_holders",
        Tokens.HolderController,
        only: [:index],
        as: :holder
      )

      resources(
        "/inventory",
        Tokens.InventoryController,
        only: [:index],
        as: :inventory
      )
    end

    resources(
      "/smart_contracts",
      SmartContractController,
      only: [:index, :show],
      as: :smart_contract
    )

    get("/search", ChainController, :search)

    get("/search_logs", AddressLogsController, :search_logs)

    get("/token_autocomplete", ChainController, :token_autocomplete)

    get("/chain_blocks", ChainController, :chain_blocks, as: :chain_blocks)

    get("/api_docs", APIDocsController, :index)
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
defmodule BlockScoutWeb.API.RPC.TransactionController do
  use BlockScoutWeb, :controller

  import BlockScoutWeb.Chain, only: [paging_options: 1, next_page_params: 3, split_list_by_page: 1]

  alias Explorer.Chain

  def gettxinfo(conn, params) do
    with {:txhash_param, {:ok, txhash_param}} <- fetch_txhash(params),
         {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param),
         {:transaction, {:ok, transaction}} <- transaction_from_hash(transaction_hash),
         paging_options <- paging_options(params) do
      logs = Chain.transaction_to_logs(transaction, paging_options)
      {logs, next_page} = split_list_by_page(logs)

      render(conn, :gettxinfo, %{
        transaction: transaction,
        block_height: Chain.block_height(),
        logs: logs,
        next_page_params: next_page_params(next_page, logs, params)
      })
    else
      {:transaction, :error} ->
        render(conn, :error, error: "Transaction not found")

      {:txhash_param, :error} ->
        render(conn, :error, error: "Query parameter txhash is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")
    end
  end

  def gettxreceiptstatus(conn, params) do
    with {:txhash_param, {:ok, txhash_param}} <- fetch_txhash(params),
         {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param) do
      status = to_transaction_status(transaction_hash)
      render(conn, :gettxreceiptstatus, %{status: status})
    else
      {:txhash_param, :error} ->
        render(conn, :error, error: "Query parameter txhash is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")
    end
  end

  def getstatus(conn, params) do
    with {:txhash_param, {:ok, txhash_param}} <- fetch_txhash(params),
         {:format, {:ok, transaction_hash}} <- to_transaction_hash(txhash_param) do
      error = to_transaction_error(transaction_hash)
      render(conn, :getstatus, %{error: error})
    else
      {:txhash_param, :error} ->
        render(conn, :error, error: "Query parameter txhash is required")

      {:format, :error} ->
        render(conn, :error, error: "Invalid txhash format")
    end
  end

  defp fetch_txhash(params) do
    {:txhash_param, Map.fetch(params, "txhash")}
  end

  defp transaction_from_hash(transaction_hash) do
    case Chain.hash_to_transaction(transaction_hash, necessity_by_association: %{block: :required}) do
      {:error, :not_found} -> {:transaction, :error}
      {:ok, transaction} -> {:transaction, {:ok, transaction}}
    end
  end

  defp to_transaction_hash(transaction_hash_string) do
    {:format, Chain.string_to_transaction_hash(transaction_hash_string)}
  end

  defp to_transaction_status(transaction_hash) do
    case Chain.hash_to_transaction(transaction_hash) do
      {:error, :not_found} -> ""
      {:ok, transaction} -> transaction.status
    end
  end

  defp to_transaction_error(transaction_hash) do
    with {:ok, transaction} <- Chain.hash_to_transaction(transaction_hash),
         {:error, error} <- Chain.transaction_to_status(transaction) do
      error
    else
      _ -> ""
    end
  end
end

apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
defmodule BlockScoutWeb.TransactionController do
  use BlockScoutWeb, :controller

  import BlockScoutWeb.Chain, only: [paging_options: 1, next_page_params: 3, split_list_by_page: 1]

  alias BlockScoutWeb.TransactionView
  alias Explorer.Chain
  alias Phoenix.View

  def index(conn, %{"type" => "JSON"} = params) do
    full_options =
      Keyword.merge(
        [
          necessity_by_association: %{
            :block => :required,
            [created_contract_address: :names] => :optional,
            [from_address: :names] => :optional,
            [to_address: :names] => :optional
          }
        ],
        paging_options(params)
      )

    transactions_plus_one = Chain.recent_collated_transactions(full_options)
    {transactions, next_page} = split_list_by_page(transactions_plus_one)

    next_page_path =
      case next_page_params(next_page, transactions, params) do
        nil ->
          nil

        next_page_params ->
          transaction_path(conn, :index, Map.delete(next_page_params, "type"))
      end

    json(
      conn,
      %{
        items:
          Enum.map(transactions, fn transaction ->
            View.render_to_string(
              TransactionView,
              "_tile.html",
              transaction: transaction
            )
          end),
        next_page_path: next_page_path
      }
    )
  end

  def index(conn, _params) do
    transaction_estimated_count = Chain.transaction_estimated_count()

    render(
      conn,
      "index.html",
      current_path: current_path(conn),
      transaction_estimated_count: transaction_estimated_count
    )
  end

  def show(conn, %{"id" => id}) do
    case Chain.string_to_transaction_hash(id) do
      {:ok, transaction_hash} -> show_transaction(conn, id, Chain.hash_to_transaction(transaction_hash))
      :error -> conn |> put_status(422) |> render("invalid.html", transaction_hash: id)
    end
  end

  defp show_transaction(conn, id, {:error, :not_found}) do
    conn |> put_status(404) |> render("not_found.html", transaction_hash: id)
  end

  defp show_transaction(conn, id, {:ok, %Chain.Transaction{} = transaction}) do
    if Chain.transaction_has_token_transfers?(transaction.hash) do
      redirect(conn, to: transaction_token_transfer_path(conn, :index, id))
    else
      redirect(conn, to: transaction_internal_transaction_path(conn, :index, id))
    end
  end
end

apps/block_scout_web/lib/block_scout_web/templates/transaction/_link.html.eex
<%= link(@transaction_hash,
    to: transaction_path(BlockScoutWeb.Endpoint, :show, @transaction_hash),
    "data-test": "transaction_hash_link",
    class: "text-truncate") %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_metatags.html.eex
<%= if assigns[:transaction] do %>
  <title>
    <%= gettext(
          "Transaction %{transaction} - %{subnetwork} Explorer",
          transaction: to_string(@transaction.hash),
          subnetwork: BlockScoutWeb.LayoutView.subnetwork_title()
        ) %>
  </title>

  <meta name="description" content="<%= gettext "View transaction %{transaction} on %{subnetwork}", transaction: to_string(@transaction.hash), subnetwork: BlockScoutWeb.LayoutView.subnetwork_title() %>">
  <meta name="keywords" content="<%= gettext "Transaction %{transaction}, %{subnetwork} %{transaction}", transaction: to_string(@transaction.hash), subnetwork: BlockScoutWeb.LayoutView.subnetwork_title() %>">
<% else %>
  <%= BlockScoutWeb.LayoutView.render("_default_title.html") %>
<% end %>

apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
<div class="text-nowrap row mt-3 mt-sm-0" data-test="token_transfer">
  <span class="col-12 col-md-5">
    <%= if from_or_to_address?(@token_transfer, @address) do %>
      <%= if @token_transfer.from_address_hash == @address.hash do %>
        <span data-test="transaction_type" class="text-danger">
            &#8627;
        </span>
      <% else %>
        <span data-test="transaction_type" class="text-success">
            &#8627;
        </span>
      <% end %>
    <% end %>
    <span class="d-inline-block tile-type-token-transfer-short-name">
    <%= @token_transfer |> BlockScoutWeb.AddressView.address_partial_selector(:from, @address, true) |> BlockScoutWeb.RenderHelpers.render_partial() %>
    </span>
    &rarr;
    <span class="d-inline-block tile-type-token-transfer-short-name">
    <%= @token_transfer |> BlockScoutWeb.AddressView.address_partial_selector(:to, @address, true) |> BlockScoutWeb.RenderHelpers.render_partial() %>
    </span>
  </span>
  <span class="col-12 col-md-7 ml-3 ml-sm-0">
  <%= token_transfer_amount(@token_transfer) %>
  <%= link(token_symbol(@token_transfer.token), to: token_path(BlockScoutWeb.Endpoint, :show, @token_transfer.token.contract_address_hash)) %>
  </span>
</div>

apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
<% block = @transaction.block %>
<% decoded_input_data = decoded_input_data(@transaction) %>
<% status = transaction_status(@transaction) %>
<section data-page="transaction-details" data-page-transaction-hash="<%= @transaction %>">
  <div class="row">
    <div class="col-md-12 col-lg-8 pr-0-md">
      <!-- Transaction Details -->
      <div class="card card-mr-50-md">
        <div class="card-body">
          <h1 class="card-title">
            <%= gettext "Transaction Details" %>
            <!-- buttons -->
            <span class="overview-title-buttons float-right">
              <span data-clipboard-text="<%= @transaction %>">
                <span
                  aria-label='<%= gettext("Copy Transaction Hash") %>'
                  class="btn-copy-icon"
                  data-placement="top"
                  data-toggle="tooltip"
                  title='<%= gettext("Copy Txn Hash") %>'
                >
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.5 32.5" width="32" height="32">
                    <path fill-rule="evenodd" d="M23.5 20.5a1 1 0 0 1-1-1v-9h-9a1 1 0 0 1 0-2h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zm-3-7v10a1 1 0 0 1-1 1h-10a1 1 0 0 1-1-1v-10a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1zm-2 1h-8v8h8v-8z"/>
                  </svg>
                </span>
              </span>
            </span>
          </h1>
          <%= if status == :pending do %>
            <div class="tile tile-muted d-flex justify-content-center align-items-center mb-4">
              <div class="loading-spinner">
                <span class="loading-spinner-block-1"></span>
                <span class="loading-spinner-block-2"></span>
              </div>
              <%= gettext("This transaction is pending confirmation.") %>
            </div>
          <% end %>
          <h3 class="transaction-details-address" data-test="transaction_detail_hash"><%= @transaction %> </h3>
          <span class="d-block mb-2 text-muted">
            <%= @transaction |> BlockScoutWeb.AddressView.address_partial_selector(:from, nil) |> BlockScoutWeb.RenderHelpers.render_partial() %>
            <span class="text-muted">  &rarr; </span>
            <%= @transaction |> BlockScoutWeb.AddressView.address_partial_selector(:to, nil) |> BlockScoutWeb.RenderHelpers.render_partial() %>
          </span>
          <div class="d-flex flex-row justify-content-start text-muted">
            <span class="mr-4 text-<%= BlockScoutWeb.TransactionView.type_suffix(@transaction) %>"><%= BlockScoutWeb.TransactionView.transaction_display_type(@transaction) %></span>
            <span class="mr-4" data-transaction-status="<%= BlockScoutWeb.TransactionView.formatted_status(status) %>"><%= BlockScoutWeb.TransactionView.formatted_status(status) %></span>
            <span class="mr-4">
              <%= if block do %>
                <span data-from-now="<%= @transaction.block.timestamp %>"></span>
              <% end %>
            </span>
          </div>
          <!-- Verify in other explorers -->
          <!-- <%= render BlockScoutWeb.AddressView, "_verify_other_explorers.html", hash: hash(@transaction), type: "tx" %> -->
          <hr>
          <!-- Block Hash -->
          <dl class="row">
            <dt class="col-sm-3 text-muted"><%= gettext "Block Number" %> </dt>
            <dd class="col-sm-9" data-selector="block-number">
              <%= if block do %>
                <%= link(
                      block,
                      class: "transaction__link",
                      to: block_path(@conn, :show, block)
                    ) %>
              <% else %>
                <%= formatted_status(status) %>
              <% end %>
            </dd>
          </dl>
          <dl class="row">
            <dt class="col-sm-3 text-muted"><%= gettext "Block Confirmations" %></dt>
            <dd class="col-sm-9">
              <span data-selector="block-confirmations"><%= confirmations(@transaction, block_height: @block_height) %></span>
          </dd>
          </dl>
          <!-- Nonce -->
          <dl class="row">
            <dt class="col-sm-3 text-muted"> <%= gettext "Nonce" %> </dt>
            <dd class="col-sm-9"> <%= @transaction.nonce %> </dd>
          </dl>
          <!-- TX Fee -->
          <dl class="row">
            <dt class="col-sm-3 text-muted"> <%= gettext "TX Fee" %> </dt>
            <dd class="col-sm-9">
              <%= formatted_fee(@transaction, denomination: :ether) %>

              <%= if !empty_exchange_rate?(@exchange_rate) do %>
                (<span data-wei-value=<%= fee(@transaction) %> data-usd-exchange-rate=<%= @exchange_rate.usd_value %>></span>)
              <% end %>
            </dd>
          </dl>
          <!-- Processing Time -->
          <%= case processing_time_duration(@transaction) do %>
            <% :pending -> %>
              <% nil %>
            <% :unknown -> %>
              <% nil %>
            <% {:ok, interval_string} -> %>
              <dl class="row">
                <dt class="col-sm-3 text-muted"> <%= gettext "Transaction Speed" %> </dt>
                <dd class="col-sm-9">
                  <%= interval_string %>
                </dd>
              </dl>
          <% end %>
          <%= unless value_transfer?(@transaction) do %>
            <dl class="row">
              <dt class="col-sm-3 text-muted"><%= gettext "Raw Input" %></dt>
              <dd class="col-sm-9">
                <div class="d-flex mb-1 justify-content-between">
                  <!-- Dropdown -->
                  <div class="dropdown">
                    <button class="btn-dropdown-line dropdown-toggle" type="button" id="tx-input-decoding-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <%= gettext("Hex (Default)") %>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="transaction-input-decoding-button">
                      <a href class="dropdown-item tx-input-dropdown" data-target=".tx-raw-input" id="tx-dropdown-raw">
                        <%= gettext("Hex (Default)") %>
                      </a>
                      <a href class="dropdown-item tx-input-dropdown" data-target=".tx-utf8-input" id="tx-dropdown-utf8">
                        <%= gettext("UTF-8") %>
                      </a>
                    </div>
                  </div>
                  <!-- Copy -->
                  <span
                    aria-label="Copy Value"
                    class="btn-copy-icon tx-raw-input transaction-input"
                    id="tx-raw-input"
                    data-clipboard-text="<%= @transaction.input %>"
                    data-placement="top"
                    data-toggle="tooltip"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.5 32.5" width="32" height="32">
                      <path fill-rule="evenodd" d="M23.5 20.5a1 1 0 0 1-1-1v-9h-9a1 1 0 0 1 0-2h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zm-3-7v10a1 1 0 0 1-1 1h-10a1 1 0 0 1-1-1v-10a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1zm-2 1h-8v8h8v-8z"/>
                    </svg>
                  </span>
                  <!-- Copy -->
                  <span
                    aria-label="Copy Value"
                    class="btn-copy-icon tx-utf8-input transaction-input"
                    data-clipboard-text="<%= @transaction.input %>"
                    data-placement="top"
                    data-toggle="tooltip"
                    style="display: none;"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.5 32.5" width="32" height="32">
                      <path fill-rule="evenodd" d="M23.5 20.5a1 1 0 0 1-1-1v-9h-9a1 1 0 0 1 0-2h10a1 1 0 0 1 1 1v10a1 1 0 0 1-1 1zm-3-7v10a1 1 0 0 1-1 1h-10a1 1 0 0 1-1-1v-10a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1zm-2 1h-8v8h8v-8z"/>
                    </svg>
                  </span>
                </div>
                <!-- Textarea -->
                <div class="transaction-input tx-raw-input">
                  <div class="tile tile-muted">
                    <pre class="pre-scrollable pre-scrollable-shorty pre-wrap mb-0"><code><%= @transaction.input %></code></pre>
                  </div>
                </div>
                <!-- Textfield -->
                <div class="transaction-input tx-utf8-input" style="display: none;">
                  <div class="tile tile-muted">
                    <pre class="pre-scrollable pre-scrollable-shorty pre-wrap mb-0"><code><%= @transaction.input.bytes %></code></pre>
                  </div>
                </div>
              </dd>
            </dl>
          <% end %>
        </div>
      </div>
    </div>

    <%= cond do %>
      <% erc20_token_transfer = assigns[:token_transfers] && erc20_token_transfer(@transaction, @token_transfers) -> %>

        <div class="col-md-12 col-lg-4 d-flex flex-column flex-md-row flex-lg-column pl-0">
        <!-- Value -->
        <div class="card card-background-1 flex-grow-1">
          <div class="card-body card-body-flex-column-space-between">
            <h2 class="card-title balance-card-title"><%= gettext "ERC-20" %> <%= gettext "Token Transfer" %></h2>
            <div class="text-right">
              <h3 class="address-balance-text">
                  <%= token_transfer_amount(erc20_token_transfer) %>
                  <%= link(token_symbol(erc20_token_transfer.token), to: token_path(BlockScoutWeb.Endpoint, :show, erc20_token_transfer.token.contract_address_hash)) %>
              </h3>
            </div>
          </div>
        </div>
      <% erc721_token_transfer = assigns[:token_transfers] && erc721_token_transfer(@transaction, @token_transfers) -> %>
        <div class="col-md-12 col-lg-4 d-flex flex-column flex-md-row flex-lg-column">
        <!-- Value -->
        <div class="card card-primary flex-grow-1">
          <div class="card-body">
            <h2 class="card-title text-white"><%= gettext "ERC-721" %> <%= gettext "Token Transfer" %></h2>
            <div class="text-right">
              <h3 class="text-white">
                <span class="col-12 col-md-7 ml-3 ml-sm-0">
                  <%= token_transfer_amount(erc721_token_transfer) %>
                  <%= link(token_symbol(erc721_token_transfer.token), to: token_path(BlockScoutWeb.Endpoint, :show, erc721_token_transfer.token.contract_address_hash)) %>
                </span>
              </h3>
            </div>
          </div>
        </div>
      <% true -> %>
        <div class="col-md-12 col-lg-4 d-flex flex-column flex-md-row flex-lg-column pl-0-md">
        <!-- Value -->
        <div class="card card-background-1 flex-grow-1">
          <div class="card-body card-body-flex-column-space-between">
            <h2 class="card-title balance-card-title"><%= gettext "Ether" %> <%= gettext "Value" %></h2>
            <div class="text-right">
              <h3 class="address-balance-text">
                <%= value(@transaction) %>
              </h3>
              <%= if !empty_exchange_rate?(@exchange_rate) do %>
                <p class="address-current-balance" 
                  data-wei-value=<%= @transaction.value.value %> 
                  data-usd-exchange-rate=<%= @exchange_rate.usd_value %>>
                </p>
              <% end %>
            </div>
          </div>
      </div>
    <% end %>
      <!-- Gas -->
      <div class="card flex-grow-1 ml-0 ml-md-5 ml-lg-0">
        <div class="card-body card-body-flex-column-space-between">
          <h2 class="card-title balance-card-title"> <%= gettext "Gas" %> </h2>
          <div class="text-right">
            <!-- Gas Used -->
            <h3 class="address-balance-text">
              <%= gettext "Used" %>
              <%= gas_used(@transaction) %> @
              <%= gas_price(@transaction, :gwei) %>
            </h3>
            <!-- Gas Limit -->
            <p class="address-current-balance">
              <%= gettext "Limit" %>
              <%= format_gas_limit(@transaction.gas) %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= unless skip_decoding?(@transaction) do %>
    <div class="row">
      <div class="col-md-12">
        <%= render BlockScoutWeb.TransactionView, "_decoded_input.html", Map.put(assigns, :decoded_input_data, decoded_input_data) %>
      </div>
    </div>
  <% end %>

</section>